# dataset options
final: false
dataset_name: ShapenetAtlas
select_classes: []
input_points: 2500
translation: false
rotation: false

# model options
model_head: AE
encoder_name: LDGCNN
decoder_name: PCGen
components: 1
filtering: true
k: 20
cw_dim: 1024

# training
recon_loss: 'Chamfer'
load: false
load_checkpoint: 0  #0 loads last
batch_size: 16
m_training: 0
m_test: 0
opt_name: AdamW
lr: 0.0001
wd: 0.000001
epochs: 350
decay_steps: 250
min_decay: 0.01
checkpoint: 50

# utility settings
no_cuda: false
seed: 0 # 0 when no seed
viz: []
interactive_plot: false

