# dataset options
final: false
dataset_name: ShapenetAtlas
select_classes: []
input_points: 2500
translation: false
rotation: false
resample: false
batch_size: 16

# model options
model_head: AE
encoder_name: LDGCNN
decoder_name: PCGen
components: 1
filtering: false
k: 20
w_dim: &w_dim 1024

# PCGen options
sample_dim: 16
hidden_dims: [256, *w_dim, 512, 512, 512, 64]
act: ReLU

# optimization options
recon_loss: 'Chamfer'
m_training: 0
opt_name: AdamW
lr: 0.0001
wd: 0.000001
min_decay: 0.01
decay_steps: 250
epochs: 350

# evaluation options
m_test: 0
eval_train: false
training_plot: false
de_normalize: false

# utility settings
load: false
load_checkpoint: -1  #-1 loads last
checkpoint: 50
cuda: true
seed: 0 # 0 when no seed

# visualization options
viz: [1, 10, 100, 1000]
interactive_plot: true
viz_sampling_bbox: false
viz_components: false


