# dataloader options
final: false
dataset_name: ShapenetFlow
select_classes: [airplane]
input_points: 2048
translation: false
rotation: false
resample: true
batch_size: 16

# model options
model_head: VQVAE
encoder_name: LDGCNN
decoder_name: PCGen
components: 4
filtering: true
k: 20
w_dim: &w_dim 512

# PCGen options
sample_dim: 16
hidden_dims: [256, *w_dim, 512, 512, 512, 64]
act: ReLU

# optimization options
recon_loss: 'ChamferEMD'
m_training: 0
opt_name: Adam
lr: 0.001
wd: 0.
min_decay: 0.01
decay_steps: 900
epochs: 1000

# evaluation options
m_test: 0
eval_train: false
training_plot: true
de_normalize: true

# utility settings
load: false
load_checkpoint: -1  #-1 loads last
checkpoint: 10
cuda: true
seed: 0 # 0 when no seed

# VQVAE
book_size: 16
embedding_dim: 4
z_dim: 32
c_commitment: 2
c_embedding: 2
vq_ema_update: false
vq_noise: 1.

# second encoding options
c_kld: 3
vae_load: false
vae_batch_size: 128
vae_n_pseudo_inputs: 400
vae_opt_name: Adam
vae_lr: 0.001
vae_wd: 0.00
vae_min_decay: 0.01
vae_decay_period: 250
vae_epochs: 300
vae_checkpoint: 10
vae_dropout: 0.0

# visualization options
viz: [1, 10, 100, 200]
interactive_plot: true
viz_double_encoding: false
add_viz:

# generation options
gen: 3

# evaluate samplings options
ch_tests: 10
emd_tests: 0