# dataset options
final: false
dataset_name: ShapenetFlow
select_classes: [airplane]
input_points: 2048
translation: false
rotation: false

# model options
model_head: VQVAE
encoder_name: LDGCNN
decoder_name: PCGen
components: 4
filtering: true
k: 20
cw_dim: 512

# training
recon_loss: 'ChamferEMD'
load: false
load_checkpoint: 0  #0 loads last
batch_size: 16
m_training: 0
m_test: 0
opt_name: Adam
lr: 0.001
wd: 0.
min_decay: 1
epochs: 1000
decay_steps: 900
checkpoint: 10

# utility settings
no_cuda: false
seed: 0 # 0 when no seed
viz: []
gen: 1
interactive_plot: false

# VQVAE
book_size: 16
embedding_dim: 4
z_dim: 32
c_commitment: 10

# training second encoding
c_kld: 2
vae_load: true
vae_batch_size: 128
vae_pseudo_inputs: 400
vae_opt_name: Adam
vae_lr: 0.001
vae_wd: 0
vae_epochs: 1000
vae_decay_period: 900
vae_min_decay: 0.01
vae_checkpoint: 1000
