# dataset options
final: false
dataset_name: ShapenetFlow
select_classes: [airplane]
input_points: 2048
translation: false
rotation: false
resample: true

# model options
model_head: VQVAE
encoder_name: LDGCNN
decoder_name: PCGen
components: 4
filtering: true
k: 20
cw_dim: 512

# training
recon_loss: 'ChamferEMD'
load: false
load_checkpoint: 0  #0 loads last
batch_size: 16
m_training: 0
m_test: 0
opt_name: Adam
lr: 0.001
wd: 0.
min_decay: 0.01
epochs: 1000
decay_steps: 900
checkpoint: 10

# VQVAE
book_size: 16
embedding_dim: 4
z_dim: 32
c_commitment: 2
c_embedding: 2
vq_ema_update: false
vq_noise: 0.01

# training second encoding
c_kld: 2
vae_load: true
vae_batch_size: 128
vae_pseudo_inputs: 400
vae_opt_name: Adam
vae_lr: 0.001
vae_wd: 0
vae_epochs: 1000
vae_decay_period: 900
vae_min_decay: 0.01
vae_checkpoint: 1000

# evaluation options
eval_train: false
viz: [1, 10, 100, 200]
training_plot: true
interactive_plot: true
de_normalize: true

# utility settings
cuda: true
seed: 0 # 0 when no seed